#!/bin/bash
# salt installeren

apt-get update -y
curl -L https://bootstrap.saltstack.com/ -o install_salt.sh
sh install_salt.sh
apt-get upgrade -y

# definieer salt master

echo “master: 10.0.6.53” >> /etc/salt/minion 
salt-minion -d
systemctl restart salt-minion.service
